FROM python:3.11-slim

WORKDIR /app
COPY api/ .
COPY database.py .

RUN pip install -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["python", "server_api.py", "--api_host", "0.0.0.0", "--api_port", "8000", "--db_host", "redis", "--db_port", "6379"]