apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/network-tier: Standard
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  type: LoadBalancer
  loadBalancerIP: 35.210.136.63
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
