apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: main
  name: main
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: main
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: main
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/flights-co2-tracker-389215/docker-images/main:latest
          imagePullPolicy: Always
          name: main
          resources: {}
          volumeMounts:
            - name: account-data-volume
              mountPath: /config
      volumes:
        - name: account-data-volume
          configMap:
            name: account-data-configmap
      restartPolicy: Always
  revisionHistoryLimit: 1
status: {}
