steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/flights-co2-tracker-389215/api:latest', './dockerfiles/Dockerfile.api' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/flights-co2-tracker-389215/main:latest', './dockerfiles/Dockerfile.main' ]
images:
- 'gcr.io/flights-co2-tracker-389215/api:latest'
- 'gcr.io/flights-co2-tracker-389215/main:latest'
