name: Deploy to GCP

on:
  push:
    branches:
      - main

    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  testing:
    uses: ./.github/workflows/python-linting-testing.yaml
  deployment:
    runs-on: ubuntu-latest
    needs: [testing]
    
    # Set default working directory
    defaults:
        run:
          working-directory: ./server

    env:
        PROJECT_ID: flights-co2-tracker-389215

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Google cloud authentication
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      # Configuration of the Google Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'

      # Build Docker Images and push to Google Container Registry
      - name: 'Build and Push Docker Images'
        run: |
          docker build . -t main:latest -f .dockerfiles/Dockerfile.main
          docker tag main:latest europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-images/main:latest
          docker push europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-images/main:latest
          docker build . -t api:latest -f .dockerfiles/Dockerfile.api
          docker tag api:latest europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-images/api:latest
          docker push europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-images/api:latest

      # Deploy Docker images to Compute Engine
      - name: Deploy to Compute Engine
        run: |
            gcloud compute instances update-container co2-flight-tracker \
            --container-image europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-images/api:latest \
            --container-network carbon_network \
            --zone europe-west1-b

            gcloud compute instances update-container co2-flight-tracker \
            --container-image europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-images/main:latest \
            --container-network carbon_network \
            --container-arg="--db_host" \
            --container-arg="redis" \
            --container-arg="--db_port" \
            --container-arg="6379" \
            --container-arg="--accounts" \
            --container-arg="${{ secrets.ACCOUNTS_CONFIG }}" \
            --zone europe-west1-b
        
