name: python-linting-testing

on: 
  push:

jobs:
  linting-and-testing:
    # specifies the os that the job will run on 
    runs-on: ubuntu-latest

    # set default working directory
    defaults:
        run:
          working-directory: ./server

    steps:
    # downloads the repository code to the runner's file system for workflow access
    - uses: actions/checkout@v2
       
    # sets up python environment with specified version 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # installs dependencies from requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt

    # run ruff on Python files
    - name: Run linter
      run: ruff ./

    # run static type checker on Python files
    - name: Run type checker
      run: mypy ./

    # run tests
    - name: Run tests
      run: python -m pytest