name: Lint and Format Typescript Code

on:
  pull_request:
    branches: [main]

jobs:
  lint_format:
    name: Lint and Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Format Code
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply linting and formatting changes
          branch: ${{ github.head_ref }}
