name: Lint and Format Typescript Code

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint and Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          # VALIDATE_ALL_CODEBASE: false
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: client
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: tsconfig.json
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.js
