name: Lint and Format Typescript Code

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: client
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: tsconfig.json
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.js
